# config.yml

email_settings:
  smtp: # CAMBIO: De 'aws_ses' a 'smtp'
    host: "email-smtp.us-east-1.amazonaws.com" # EJEMPLO: Servidor SMTP de AWS SES
    port: 587                 # Puerto común para TLS (o 465 para SSL directo, o 25)
    use_tls: true             # Poner en true si el servidor usa STARTTLS (común con puerto 587 o 25)
    # use_ssl: false            # Poner en true si es conexión SSL directa (común con puerto 465)
    
    username: "TU_USUARIO_SMTP_IAM_o_SIMILAR" # Usuario para autenticarse en el servidor SMTP
    # La contraseña SMTP se tomará del archivo .env (SMTP_PASSWORD)

    sender_email: "tu_correo_remitente_verificado@example.com" # Dirección 'De:' que se mostrará
    recipient_emails: # Lista de destinatarios (esto ya lo tenías)
      - "destinatario1@example.com"
      - "destinatario2@example.com"

# ... (wazuh_monitoring, disk_monitoring y global_settings sin cambios) ...
wazuh_monitoring:
  services:
    - "wazuh-manager"
    - "wazuh-indexer"
    - "wazuh-dashboard"

disk_monitoring:
  monitored_paths:
    - path: "/"
      threshold_percentage: 50
    - path: "/var"
      threshold_percentage: 15

global_settings:
  log_level: "INFO"
