# config.yml

email_settings:
  smtp: 
    host: "email-smtp.us-east-1.amazonaws.com" 
    port: 587                 # Puerto común para TLS (o 465 para SSL directo, o 25)
    use_tls: true             # Poner en true si el servidor usa STARTTLS (común con puerto 587 o 25)

    sender_email: "example@compañia.com" # Dirección 'De:' que se mostrará
    recipient_emails: # Lista de destinatarios (esto ya lo tenías)
      - "usuario1@empresa.com"
      - "usuario2@empresa.com"

# ... (wazuh_monitoring, disk_monitoring y global_settings sin cambios) ...
wazuh_monitoring:
  services:
    - "wazuh-manager"
    - "wazuh-indexer"
    - "wazuh-dashboard"

#Si el espacio libre en los path monitoreados es menor al umbral, la alerta se dispara.
disk_monitoring:
  monitored_paths:
    - path: "/"
      threshold_percentage: 10
    - path: "/mnt/datos"
      threshold_percentage: 10

# NUEVA SECCIÓN PARA MONITOREAR EL INDEXER
indexer_monitoring:
  # Ponlo en 'true' para activar esta revisión
  enabled: true

  # IP del servidor donde corre el Wazuh Indexer
  ip: "127.0.0.1"

  # Puerto de la API del Wazuh Indexer (usualmente 9200)
  port: 9200

  # Umbral en minutos. Si no hay eventos nuevos en este tiempo, se generará una alerta.
  minutes_threshold: 1

  # Índices a consultar. Generalmente no necesitas cambiar esto.
  indices_pattern: "wazuh-alerts-*"

global_settings:
  log_level: "INFO"
